#!/usr/bin/env python3
"""Phase 0 native-vs-Vfs workload baseline harness."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path
from statistics import mean
from typing import Any, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib.common import (  # noqa: E402
    env_flag,
    parse_json_stdout,
    positive_float,
    positive_int,
    resolve_vfs_bin,
    run_subprocess,
    sandbox_python,
)

SYNTHETIC_WORKLOAD = r'''#!/usr/bin/env python3
import hashlib
import json
from pathlib import Path

root = Path.cwd()
inputs = []
for dirname in ("src", "tests", "docs"):
    base = root / dirname
    if base.exists():
        inputs.extend(path for path in sorted(base.rglob("*")) if path.is_file())

digest = hashlib.sha256()
total_bytes = 0
for path in inputs:
    data = path.read_bytes()
    digest.update(str(path.relative_to(root)).encode("utf-8"))
    digest.update(b"\0")
    digest.update(data)
    total_bytes += len(data)

out_dir = root / "build" / "baseline"
out_dir.mkdir(parents=True, exist_ok=True)
manifest = {
    "digest": digest.hexdigest(),
    "input_bytes": total_bytes,
    "input_files": len(inputs),
}
(out_dir / "manifest.json").write_text(
    json.dumps(manifest, indent=2, sort_keys=True) + "\n",
    encoding="utf-8",
)

for index, path in enumerate(inputs[:16]):
    rel = path.relative_to(root)
    payload = f"{index:02d} {rel} {path.stat().st_size}\n"
    (out_dir / f"artifact_{index:02d}.txt").write_text(payload, encoding="utf-8")

generated = root / "src" / "pkg00" / "generated_baseline.py"
generated.write_text(
    "# generated by workload-baseline.py\n"
    f"DIGEST = {digest.hexdigest()!r}\n"
    f"INPUT_FILES = {len(inputs)}\n",
    encoding="utf-8",
)

output_bytes = 0
for path in sorted(out_dir.rglob("*")):
    if path.is_file():
        output_bytes += path.stat().st_size
        path.read_bytes()[:128]

print(json.dumps({
    "digest": digest.hexdigest(),
    "input_bytes": total_bytes,
    "input_files": len(inputs),
    "output_bytes": output_bytes,
}, sort_keys=True))
'''


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compare a workload on native filesystem storage against the same "
            "workload under a Vfs copy-on-write overlay."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  # Fast deterministic smoke workload
  scripts/validation/workload-baseline.py

  # Shell command from a real source checkout, copied into temp dirs by default
  scripts/validation/workload-baseline.py --source /path/to/factory-mono \\
    --command 'cargo check --workspace'

  # Command argv form
  scripts/validation/workload-baseline.py --source /path/to/factory-mono -- cargo test -p crate

Environment:
  VFS_BIN                 path/name of vfs executable
  VFS_PROFILE             set to 1 to emit Vfs profiling summaries
  WORKLOAD_BASELINE_COMMAND  shell command to run when --command is omitted
  WORKLOAD_BASELINE_SOURCE   source tree to copy when --source is omitted
""",
    )
    parser.add_argument(
        "--mode",
        choices=("synthetic", "command"),
        default=None,
        help="workload mode; defaults to synthetic unless a command is supplied",
    )
    parser.add_argument(
        "--source",
        default=os.environ.get("WORKLOAD_BASELINE_SOURCE"),
        help="source tree for command mode (default: current directory)",
    )
    parser.add_argument(
        "-c",
        "--command",
        default=os.environ.get("WORKLOAD_BASELINE_COMMAND"),
        help="shell command to run in native and Vfs worktrees",
    )
    parser.add_argument(
        "--iterations",
        type=positive_int,
        default=positive_int(os.environ.get("WORKLOAD_BASELINE_ITERATIONS", "1")),
        help="number of fresh native/Vfs comparisons to run (default: 1)",
    )
    parser.add_argument(
        "--timeout",
        type=positive_float,
        default=positive_float(os.environ.get("WORKLOAD_BASELINE_TIMEOUT", "120")),
        help="per-command timeout in seconds (default: 120)",
    )
    parser.add_argument(
        "--vfs-bin",
        default=os.environ.get("VFS_BIN"),
        help="vfs executable path/name (default: repo target binary, building cli if needed)",
    )
    parser.add_argument(
        "--compare-stdout",
        action="store_true",
        help="command mode: fail if native and Vfs stdout differ exactly",
    )
    parser.add_argument(
        "--keep-temp",
        action="store_true",
        default=env_flag("WORKLOAD_BASELINE_KEEP_TEMP"),
        help="keep temporary worktrees and isolated HOME after the run",
    )
    parser.add_argument(
        "--preserve-home",
        action="store_true",
        help="do not replace HOME/XDG directories with temp dirs for child commands",
    )
    parser.add_argument(
        "--in-place-native",
        action="store_true",
        help=(
            "run command mode directly in --source instead of temp copies; unsafe "
            "unless the workload is read-only"
        ),
    )
    parser.add_argument(
        "--exclude",
        action="append",
        default=[],
        help="shutil.ignore_patterns-style name pattern excluded when copying --source",
    )
    parser.add_argument(
        "--output",
        help="write JSON result to this file instead of stdout",
    )
    parser.add_argument(
        "--json-indent",
        type=int,
        default=2,
        help="JSON indentation level (default: 2)",
    )
    parser.add_argument(
        "argv",
        nargs=argparse.REMAINDER,
        help="command argv to run after --; mutually exclusive with --command",
    )
    args = parser.parse_args(argv)

    if args.argv and args.argv[0] == "--":
        args.argv = args.argv[1:]

    command_supplied = bool(args.command) or bool(args.argv)
    if args.mode is None:
        args.mode = "command" if command_supplied else "synthetic"

    if args.mode == "synthetic" and command_supplied:
        parser.error("synthetic mode does not accept --command or trailing argv")
    if args.mode == "command" and args.command and args.argv:
        parser.error("--command and trailing argv are mutually exclusive")
    if args.mode == "command" and not command_supplied:
        parser.error("command mode requires --command, WORKLOAD_BASELINE_COMMAND, or argv after --")

    return args


def create_synthetic_tree(root: Path) -> None:
    for package_index in range(6):
        package = root / "src" / f"pkg{package_index:02d}"
        package.mkdir(parents=True, exist_ok=True)
        (package / "__init__.py").write_text(
            f'"""Synthetic package {package_index}."""\n',
            encoding="utf-8",
        )
        for module_index in range(8):
            lines = [
                f"VALUE_{line_index} = {package_index * 1000 + module_index * 100 + line_index}\n"
                for line_index in range(32)
            ]
            lines.append(
                "\n"
                "def checksum():\n"
                "    return sum(value for name, value in globals().items() if name.startswith('VALUE_'))\n"
            )
            (package / f"module_{module_index:02d}.py").write_text(
                "".join(lines),
                encoding="utf-8",
            )

    tests = root / "tests"
    tests.mkdir(parents=True, exist_ok=True)
    for index in range(12):
        (tests / f"test_pkg_{index:02d}.py").write_text(
            "def test_placeholder():\n    assert True\n",
            encoding="utf-8",
        )

    docs = root / "docs"
    docs.mkdir(parents=True, exist_ok=True)
    for index in range(4):
        (docs / f"note_{index:02d}.md").write_text(
            f"# Synthetic note {index}\n\n" + ("Vfs baseline data.\n" * 20),
            encoding="utf-8",
        )

    (root / "pyproject.toml").write_text(
        "[project]\nname = \"vfs-baseline-synthetic\"\nversion = \"0.0.0\"\n",
        encoding="utf-8",
    )
    (root / ".vfs_baseline_workload.py").write_text(
        SYNTHETIC_WORKLOAD,
        encoding="utf-8",
    )


def copy_source_tree(source: Path, destination: Path, excludes: list[str]) -> None:
    ignore = shutil.ignore_patterns(*excludes) if excludes else None
    shutil.copytree(
        source,
        destination,
        symlinks=True,
        ignore=ignore,
        ignore_dangling_symlinks=True,
    )


def prepare_environment(temp_root: Path, preserve_home: bool) -> dict[str, str]:
    env = os.environ.copy()
    env["VFS_BASELINE"] = "1"
    env.setdefault("PYTHONDONTWRITEBYTECODE", "1")
    env.setdefault("NO_COLOR", "1")
    temp_dir = temp_root / "tmp"
    temp_dir.mkdir(parents=True, exist_ok=True)
    env["TMPDIR"] = str(temp_dir)
    env["TMP"] = str(temp_dir)
    env["TEMP"] = str(temp_dir)

    if not preserve_home:
        home = temp_root / "home"
        xdg_config = home / ".config"
        xdg_cache = home / ".cache"
        xdg_data = home / ".local" / "share"
        for path in (home, xdg_config, xdg_cache, xdg_data):
            path.mkdir(parents=True, exist_ok=True)
        env["HOME"] = str(home)
        env["XDG_CONFIG_HOME"] = str(xdg_config)
        env["XDG_CACHE_HOME"] = str(xdg_cache)
        env["XDG_DATA_HOME"] = str(xdg_data)

    return env


def command_argv(args: argparse.Namespace) -> tuple[str, str, list[str]]:
    if args.mode == "synthetic":
        python = sandbox_python()
        return ("argv", f"{python} .vfs_baseline_workload.py", [python, ".vfs_baseline_workload.py"])
    if args.command:
        return ("shell", args.command, ["sh", "-lc", args.command])
    return ("argv", " ".join(args.argv), args.argv)


def prepare_roots(args: argparse.Namespace, iteration_dir: Path) -> tuple[Path, Path]:
    native_root = iteration_dir / "native"
    vfs_root = iteration_dir / "vfs-base"

    if args.mode == "synthetic":
        create_synthetic_tree(native_root)
        create_synthetic_tree(vfs_root)
        return native_root, vfs_root

    source = Path(args.source or ".").expanduser().resolve()
    if not source.is_dir():
        raise RuntimeError(f"source tree is not a directory: {source}")

    if args.in_place_native:
        return source, source

    copy_source_tree(source, native_root, args.exclude)
    copy_source_tree(source, vfs_root, args.exclude)
    return native_root, vfs_root


def summarize_runs(iterations: list[dict[str, Any]]) -> dict[str, Any]:
    native_durations = [item["native"]["duration_seconds"] for item in iterations]
    vfs_durations = [item["vfs"]["duration_seconds"] for item in iterations]
    native_mean = mean(native_durations)
    vfs_mean = mean(vfs_durations)
    return {
        "native_seconds": native_mean,
        "vfs_seconds": vfs_mean,
        "ratio": (vfs_mean / native_mean) if native_mean > 0 else None,
    }


def compare_outputs(args: argparse.Namespace, native: dict[str, Any], vfs: dict[str, Any]) -> dict[str, Any]:
    if native["returncode"] != 0 or vfs["returncode"] != 0:
        return {"checked": False, "reason": "non-zero return code"}

    if args.mode == "synthetic":
        native_json = parse_json_stdout(native)
        vfs_json = parse_json_stdout(vfs)
        return {
            "checked": True,
            "kind": "synthetic-json-stdout",
            "equivalent": native_json == vfs_json,
            "native": native_json,
            "vfs": vfs_json,
        }

    if args.compare_stdout:
        return {
            "checked": True,
            "kind": "stdout-tail",
            "equivalent": native["stdout_tail"] == vfs["stdout_tail"],
        }

    return {"checked": False, "reason": "command mode requires --compare-stdout or external review"}


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    script_path = Path(__file__).resolve()
    repo_root = script_path.parents[2]

    temp_manager: Optional[tempfile.TemporaryDirectory[str]] = None
    if args.keep_temp:
        temp_root = Path(tempfile.mkdtemp(prefix="vfs-phase0-baseline-"))
    else:
        temp_manager = tempfile.TemporaryDirectory(prefix="vfs-phase0-baseline-")
        temp_root = Path(temp_manager.name)

    exit_code = 0
    result: dict[str, Any]
    try:
        vfs_bin = resolve_vfs_bin(args.vfs_bin, repo_root)
        env = prepare_environment(temp_root, args.preserve_home)
        command_kind, command_display, native_command = command_argv(args)
        vfs_command = [vfs_bin, "run", "--no-default-allows", "--"] + native_command

        iterations = []
        for index in range(args.iterations):
            iteration_dir = temp_root / f"iteration-{index + 1:02d}"
            iteration_dir.mkdir(parents=True, exist_ok=True)
            native_root, vfs_root = prepare_roots(args, iteration_dir)

            native = run_subprocess(native_command, native_root, env, args.timeout)
            vfs = run_subprocess(vfs_command, vfs_root, env, args.timeout)
            equivalence = compare_outputs(args, native, vfs)
            ratio = None
            if native["duration_seconds"] > 0:
                ratio = vfs["duration_seconds"] / native["duration_seconds"]
            iterations.append(
                {
                    "index": index + 1,
                    "native_root": str(native_root),
                    "vfs_base_root": str(vfs_root),
                    "native": native,
                    "vfs": vfs,
                    "equivalence": equivalence,
                    "ratio": ratio,
                }
            )
            if native["returncode"] != 0 or vfs["returncode"] != 0:
                exit_code = 1
            if equivalence.get("checked") and not equivalence.get("equivalent"):
                exit_code = 1

        result = {
            "schema_version": 1,
            "mode": args.mode,
            "command": {
                "kind": command_kind,
                "display": command_display,
            },
            "vfs": {
                "bin": vfs_bin,
                "overlay_command_prefix": [vfs_bin, "run", "--no-default-allows", "--"],
                "profile_enabled": env_flag("VFS_PROFILE"),
                "profile_summary_count": sum(
                    len(item["vfs"].get("profile_summaries", [])) for item in iterations
                ),
            },
            "source": {
                "path": str(Path(args.source or ".").expanduser().resolve()) if args.mode == "command" else None,
                "copied_to_temp": args.mode != "command" or not args.in_place_native,
                "in_place_native": bool(args.in_place_native),
                "excludes": args.exclude,
            },
            "summary": summarize_runs(iterations),
            "iterations": iterations,
            "temp_dir": str(temp_root),
            "kept_temp": bool(args.keep_temp),
            "preserve_home": bool(args.preserve_home),
            "temp_isolated": True,
            "timeout_seconds": args.timeout,
        }
    except Exception as exc:  # keep failures machine-readable for runners
        exit_code = 1
        result = {
            "schema_version": 1,
            "error": str(exc),
            "temp_dir": str(temp_root),
            "kept_temp": bool(args.keep_temp),
        }

    payload = json.dumps(result, indent=args.json_indent, sort_keys=True) + "\n"
    if args.output:
        Path(args.output).write_text(payload, encoding="utf-8")
        print(f"Wrote workload baseline JSON to {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(payload)

    if temp_manager is not None:
        temp_manager.cleanup()

    return exit_code


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
