[package]
name = "vfs-core"
version.workspace = true
edition.workspace = true
description = "Vfs SDK for Rust"
license.workspace = true

[lints]
workspace = true

[dependencies]
tokio-rusqlite = { workspace = true }
mimalloc = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
libc = { workspace = true }
thiserror = { workspace = true }
lru = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
parking_lot = { workspace = true }
smallvec = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }
proptest = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }

[[bench]]
name = "overlayfs"
harness = false

[[bench]]
name = "workload"
harness = false


[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_Globalization"] }
